# -*- coding: utf-8 -*-

COMMON: &common
  VERSION: '0.0.1'

  DEBUG: false
  TESTING: false

  LOG_BASE_DIR: 'logs'
  JINJA2_CACHE_SIZE: 50

  MONGO_URL: 'mongodb://localhost:27017/'
  MONGO_CONNECT_EAGERLY: true
  MONGO_DB: 'reddit'
  MONGO_COLLECTION_SENTENCES: 'sentences'

  MOUNT_POINT: '/api'

DEVELOPMENT: &development
  <<: *common
  DEBUG: true

  MONGO_DB: 'reddit'

  # don't cache compiled templates: means we can edit on the fly during development
  JINJA2_CACHE_SIZE: 0

TEST: &test
  <<: *common

  MONGO_DB: 'krump_test'

  TESTING: true

PRODUCTION: &production
  <<: *common

  MONGO_DB: 'krump_prod'

  JSONIFY_PRETTYPRINT_REGULAR: false
