# -*- coding: utf-8 -*-

COMMON: &common
  VERSION: '0.0.1'

  DEBUG: false
  TESTING: false

  LOG_BASE_DIR: 'logs'
  JINJA2_CACHE_SIZE: 50

  MOUNT_POINT: '/api'

DEVELOPMENT: &development
  <<: *common
  DEBUG: true

  # don't cache compiled templates: means we can edit on the fly during development
  JINJA2_CACHE_SIZE: 0

TEST: &test
  <<: *common

  TESTING: true

PRODUCTION: &production
  <<: *common

  JSONIFY_PRETTYPRINT_REGULAR: false
